const employees = [
    {
        id: 1,
        firstName: "vivek",
        email: "vivek@me.com",
        password: "123",
        taskCounts: {
            active: 2,
            newTask: 1,
            completed: 1,
            failed: 0,
        },
        bestAt: "UI/UX Design", 
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Update website",
                taskDescription: "Re-map the homepage design",
                taskDate: "2024-10-12",
                category: "Design",
            },
            {
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                taskTitle: "Client meeting",
                taskDescription: "Discuss project requirements",
                taskDate: "2024-10-10",
                category: "Meeting",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Fix bugs",
                taskDescription: "Resolve bugs reported in issue tracker",
                taskDate: "2024-10-14",
                category: "Development",
            },
        ],
    },
    {
        id: 2,
        firstName: "sriram",
        email: "sriram@me.com",
        password: "123",
        taskCounts: {
            active: 1,
            newTask: 0,
            completed: 1,
            failed: 0,
        },
        bestAt: "Database Optimization", 
        tasks: [
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Database optimization",
                taskDescription: "Optimize queries for better performance",
                taskDate: "2024-10-11",
                category: "Database",
            },
            {
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                taskTitle: "Design new feature",
                taskDescription: "Create mockups for the new feature",
                taskDate: "2024-10-09",
                category: "Design",
            },
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Backend Database Migration",
                taskDescription: "Migrate database to a new platform",
                taskDate: "2024-10-15",
                category: "Database",
            },
        ],
    },
    {
        id: 3,
        firstName: "arjun",
        email: "arjun@me.com",
        password: "123",
        taskCounts: {
            active: 2,
            newTask: 1,
            completed: 1,
            failed: 0,
        },
        bestAt: "Code Optimization", 
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Prepare presentation",
                taskDescription: "Prepare slides for upcoming client presentation",
                taskDate: "2024-10-13",
                category: "ppt",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Code review",
                taskDescription: "Review the codebase for optimization",
                taskDate: "2024-10-12",
                category: "Development",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Improve algorithm",
                taskDescription: "Optimize the sorting algorithm for efficiency",
                taskDate: "2024-10-16",
                category: "Development",
            },
        ],
    },
    {
        id: 4,
        firstName: "praveen",
        email: "praveen@me.com",
        password: "123",
        taskCounts: {
            active: 2,
            newTask: 1,
            completed: 0,
            failed: 0,
        },
        bestAt: "API'S", 
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Write documentation",
                taskDescription: "Update the project documentation",
                taskDate: "2024-10-13",
                category: "Documentation",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Set up CI/CD",
                taskDescription: "Implement continuous integration pipeline",
                taskDate: "2024-10-11",
                category: "DevOps",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Create API Endpoints",
                taskDescription: "Develop new RESTful endpoints for the app",
                taskDate: "2024-10-20",
                category: "Development",
            },
        ],
    },
    {
        id: 5,
        firstName: "shiva",
        email: "shiva@me.com",
        password: "123",
        taskCounts: {
            active: 2,
            newTask: 1,
            completed: 1,
            failed: 0,
        },
        bestAt: "Frontend Development", 
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "UI redesign",
                taskDescription: "Redesign the user interface for better UX",
                taskDate: "2024-10-14",
                category: "Design",
            },
            {
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                taskTitle: "Deploy new build",
                taskDescription: "Deploy the latest build to production",
                taskDate: "2024-10-09",
                category: "DevOps",
            },
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Refactor Homepage",
                taskDescription: "Improve homepage layout and performance",
                taskDate: "2024-10-22",
                category: "Frontend",
            },
        ],
    },
    {
        id: 6,
        firstName: "ajay",
        email: "ajay@me.com",
        password: "123",
        taskCounts: { active: 1, newTask: 1, completed: 0, failed: 0 },
        bestAt: "Backend Development",
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Develop REST API",
                taskDescription: "Create a RESTful API for user management",
                taskDate: "2024-10-16",
                category: "Backend",
            },
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Database integration",
                taskDescription: "Integrate database with backend APIs",
                taskDate: "2024-10-18",
                category: "Backend",
            },
        ],
    },
    {
        id: 7,
        firstName: "bhavya",
        email: "bhavya@me.com",
        password: "123",
        taskCounts: { active: 2, newTask: 1, completed: 1, failed: 0 },
        bestAt: "Data Analysis",
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Analyze user data",
                taskDescription: "Analyze the user data to find trends",
                taskDate: "2024-10-18",
                category: "Data Science",
            },
            {
                active: false,
                newTask: false,
                completed: true,
                failed: false,
                taskTitle: "Report generation",
                taskDescription: "Generate weekly data analysis reports",
                taskDate: "2024-10-20",
                category: "Data Science",
            },
        ],
    },
    {
        id: 8,
        firstName: "chitra",
        email: "chitra@me.com",
        password: "123",
        taskCounts: { active: 1, newTask: 1, completed: 0, failed: 0 },
        bestAt: "Project Management",
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Organize team meeting",
                taskDescription: "Organize a meeting for project update",
                taskDate: "2024-10-17",
                category: "Management",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Budget planning",
                taskDescription: "Plan project budget for upcoming quarter",
                taskDate: "2024-10-19",
                category: "Management",
            },
        ],
    },
    {
        id: 9,
        firstName: "deepak",
        email: "deepak@me.com",
        password: "123",
        taskCounts: { active: 1, newTask: 1, completed: 0, failed: 0 },
        bestAt: "Quality Assurance",
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Test new features",
                taskDescription: "Perform manual testing on new features",
                taskDate: "2024-10-18",
                category: "QA",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Write test cases",
                taskDescription: "Write test cases for upcoming release",
                taskDate: "2024-10-19",
                category: "QA",
            },
        ],
    },
    {
        id: 10,
        firstName: "neha",
        email: "neha@me.com",
        password: "123",
        taskCounts: { active: 2, newTask: 1, completed: 0, failed: 0 },
        bestAt: "Customer Support",
        tasks: [
            {
                active: true,
                newTask: true,
                completed: false,
                failed: false,
                taskTitle: "Resolve customer complaints",
                taskDescription: "Address customer issues reported via email",
                taskDate: "2024-10-20",
                category: "Support",
            },
            {
                active: true,
                newTask: false,
                completed: false,
                failed: false,
                taskTitle: "Create support documentation",
                taskDescription: "Update help articles for customers",
                taskDate: "2024-10-22",
                category: "Support",
            },
        ],
    }
];








const admin = [
    {
        id: 1,
        email: "admin@example.com",
        password: "123",
    },
];

export const setLocalStorage = () => {
    localStorage.setItem("employees", JSON.stringify(employees));
    localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
    const employees = JSON.parse(localStorage.getItem("employees"));
    const admin = JSON.parse(localStorage.getItem("admin"));

    return { employees, admin };
};




